- name: demo splunk
  hosts: splunk
  gather_facts: False
  tasks:
    - name: import the SplunkEnterpriseSecurity Role to access the modules
      import_role:
        name: SplunkEnterpriseSecurity
    - name: test splunk_data_input_monitor
      splunk_data_input_monitor:
        name: "/var/log/demo.log"
        state: "present"
        recursive: True
    - name: test splunk_data_input_network
      splunk_data_input_network:
        name: "9001"
        protocol: "tcp"
        state: "present"
    - name: test splunk_coorelation_search
      splunk_correlation_search:
        name: "Test Demo Coorelation Search From Playbook"
        description: "Test Demo Coorelation Search From Playbook, description."
        search: 'source="/var/log/snort.log"'
        state: "present"
    - name: test splunk_adaptive_response_notable_event
      splunk_adaptive_response_notable_event:
        name: "Demo notable event from playbook"
        correlation_search_name: "Test Demo Coorelation Search From Playbook"
        description: "Test Demo notable event from playbook, description."
        state: "present"
        next_steps:
          - ping
          - nslookup
        recommended_actions:
          - script

